### ISSUE TITLE
When will the code be released

### ISSUE THREAD

**Issue by Mrbishuai** [DAVEISHAN/TCLR#1]
Dear @DAVEISHAN 
Your research work is very meaningful and I am very interested.
But I sincerely want to know when the code can be released. I'm very eager to learn useful knowledge.
Best wishes to you！

**Comment by DAVEISHAN** [comment]
Hi, @Mrbishuai sorry for the late reply, code, and pretrained models will be uploaded soon by this weekend.

**Comment by DAVEISHAN** [comment]
@Mrbishuai Code has been released, check it out. Let me know if you have any questions.

**Comment by Mrbishuai** [comment]
Hi, @DAVEISHAN, May I ask something about the publication of the paper in Computer vision and image understanding. How long have you received the modification suggestions and how long have you finally been accepted. Because I submitted my paper in this journal some time ago, but there has been no news.

**Comment by DAVEISHAN** [comment]
I heard back in around 3 months, then revised in a few weeks and it took 2 more months. You can email me at ishandave@knights.ucf.edu for more questions related to it. 

Good luck. Closing the issue.
