### ISSUE TITLE
Embedding Size

### ISSUE THREAD

**Issue by Hussein-A-Hassan** [DAVEISHAN/TCLR#2]
Hello Sir

Thank you very much for sharing your code.
In your NN Retrieval code, you stated that the train features has size of 9537 x 4096
and the val feature has size of 3792 x 4096 for the UCF-101.

I am wondering if the r3d encoder outputs 512 x 4 which is equal to 2048 after flattening ,
how you managed to get an embedding of size 4096 ?

I tried the code and it outputs an embedding of size  2048, did I miss something here?
What is the size of the embedding for the NN-Retrieval experiments reported in the paper? 

In addition, I used the provided UCF pre-trained model to run the retrieval experiment on UCF and 
got lower accuracies than the paper:
 
torch.Size([9537, 2048]) - train features
torch.Size([3783, 2048]) - val feature

Top-1 correct is 50.44%
Top-5 correct is 69.89%
Top-10 correct is 77.27%
Top-20 correct is 84.46%
50.44, 69.89, 77.27, 84.46

Best Regards,
Hussein

**Comment by DAVEISHAN** [comment]
Hey, pl ignore the comments written in the nn retrieval code. I will clean it up soon. Also, I have uploaded the correct epoch of the UCF101 pretraining and now it is reproducing all Retrieval accuracies (Table-4, Fig-1(b), Fig 7, Supplementary Table-10) till the 4th decimal point! Thanks for noticing this. To reproduce our ablation clip wise as shown in Fig 7, change the num_modes in parameters_BL from [1,10]. Let me know if it persists.
