### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by xyall** [DAVEISHAN/TCLR#3]

**Comment by DAVEISHAN** [comment]
Please refer to [https://github.com/fmthoker/SEVERE-BENCHMARK/tree/b84d3dfdab1d9e89f36afaa9edb1dc7a048355bd/action_recognition](https://github.com/fmthoker/SEVERE-BENCHMARK/tree/b84d3dfdab1d9e89f36afaa9edb1dc7a048355bd/action_recognition) for finetuning they get even better fine-tuning performance using TCLR SSL pretrained models than our published work.
